### ISSUE TITLE
这些问题都在1.4.3修了，readme改一下

### ISSUE THREAD

**Issue by RubyLouvre** [magicapple/anujs-webpack4-ie7-8#1]
如题

**Comment by hcxowe** [comment]
@RubyLouvre 引入 anujs/dist/Router.js之后, ie8提示缺少标识符
while (node && node.nodeType == 1) {
        var checkChange = node;
        if (node.__events) {
            var vnode = node.__events.vnode;
            inner: while (vnode.return) { // 此行提示缺少标识符

**Comment by RubyLouvre** [comment]
要用es3vify转换一下

**Comment by magicapple** [comment]
已更新。
