### ISSUE TITLE
使用anujs/dist/Router.js做路由，在ie8下报SCRIPT5014: Object.prototype.propertyIsEnumerable: 'this' 不是 JavaScript 对象的错误

### ISSUE THREAD

**Issue by Mrooze-zeng** [magicapple/anujs-webpack4-ie7-8#3]
`import "core-js";
import React from "react";
import ReactDOM from "react-dom";
// import Box from './box';
// import ErrorBoundary from './errorBoundary';
// import ErrorComp from './errorComp';
// import SelectBox from './selectBox';
// import WrapBox from './wrapBox';
import { Link, Router } from "router";
const Home = () => (
   <div>
      home
      <Link to="dash">dash</Link>
   </div>
);
const Dash = () => <div>dash</div>;
const render = function render() {
   ReactDOM.render(
      <div>
         <Router>
            <Home path="/" />
            <Dash path="/dash" />
         </Router>
      </div>,
      document.getElementById("root")
   );
};

render();`

-  SCRIPT5014: Object.prototype.propertyIsEnumerable: 'this' 不是 JavaScript 对象

**Comment by magicapple** [comment]
你可以到 https://github.com/RubyLouvre/anu 给作者提问，这个只是一个 ie8 下面的脚手架，无法解决你的问题。
